### ISSUE TITLE
Feature request: skipable groups of questions?

### ISSUE THREAD

**Issue by inktrap** [cookieninja-generator/cookieninja#55]
Could we implement *skipable groups of questions?*
Groups could share a common prefix and the questions are only asked if the first question with that prefix equals the defined answer. For example:

- Do you want to do `a`? [yn]: y
- Enter `a_name`: inktrap
- Do you want to do `b`? [yn]: …

Versus

- Do you want to do `a`? [yn]: n
- Do you want to do `b`? [yn]: …

This could happen *with subgroups too,* so you could have multiple groups like `package_host_url` which is only relevant if you want to create a package in the first place and add some hosting server and only then you are asked to configure an url for that host.

Also I would like to *provide some answers* to questions, e.g. by specifying `extra_context` with the idea that the answers are used and the questions the answers belong to are not asked. (I know about `_` and `__` for variables, but I want to be able to do this with third-party packages as well, without changing their variable prefixes.)

At the same time I still want *to be able to answer questions* which are not answered yet. This would be so amazing. I could define a set of common info that should be used for all projects and that I configure once per user. Why ask for my name if you know it already? Then I could have best practices per programming language and on top of that groups of questions which depend on stuff like wether I want a package or not.

**Comment by yuvaldolev** [comment]
Hi @inktrap

Welcome to Cookieninja!
We're happy that you expressed interest in using it, and would be very happy to hear about more features that you think would be relevant to the project!

Regarding your feature request, I think we already added multiple features to Cookieninja, which weren't present in Cookiecutter, that would be suitable for implementing skippable groups of questions.

The first one is dependent questions. This feature seems to be exactly what you're searching for as it allows you to conditionally prompt for a question based on the answer for another one.
For more details about it see: https://cookieninja.readthedocs.io/en/latest/advanced/dependent_questions.html

Another feature that was recently added to Cookieninja, and might also be useful for you is dynamic choice variables. This feature allows you to display a choice question based on the answer for another question, here's an example:
json
{
    "_site_locations": {
        "zone1": ["SiteA", "SiteB", "SiteC"],
        "zone2": ["SiteD", "SiteE"],
    },
    "zone": ["zone1", "zone2"],
    "site": "{{ cookiecutter._site_locations.get(cookiecutter.zone) }}"
}

Both these features will be released as part of our 2.0.0 release, which will be coming out really soon!

I'll close this issue, but feel free to re-open it if you have any more questions regarding this subject!

Best regards,
Yuval Dolev (edited)

**Comment by inktrap** [comment]
Thanks for your detailed answer. I completely missed that you already made these changes because the README talks about cookiecutters and I had the impression that it is a recent fork with major changes to come. A comparison matrix that shows implemented features and improvements with cookiecutter might be helpful to include in the README.
