### ISSUE TITLE
Update links in `README.md` so they point to cookieninja

### ISSUE THREAD

**Issue by Havegum** [cookieninja-generator/cookieninja#57]
* Cookiecutter version: 1.0.0
* Template project url: N/A
* Python version: N/A
* Operating System: N/A

### Description:
Three of the first four links in the readme-file (documentation, github, and license) points to cookiecutter. These likely should point to cookieninja instead.

### What I've run:

Nothing. This issue pertains to these links in the documentation only.

**Comment by yuvaldolev** [comment]
Hi @Havegum
Thanks for updating the links.
We'll merge the PR and release it in the next version.
We'd love it if you'd keep working on the project and contributing more to it!
