### ISSUE TITLE
Does this proejct still alive?

### ISSUE THREAD

**Issue by SilverRainZ** [cookieninja-generator/cookieninja#78]
I known this from https://github.com/cookiecutter/cookiecutter/issues/1810, but this repo seems no longer active after fork. What is the current status and future of this project?

**Comment by inktrap** [comment]
Doesn't look like it :(

https://github.com/cookieninja-generator/cookieninja/pulse/monthly
https://github.com/cookiecutter/cookiecutter/pulse/monthly
